name: CI_build

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        build_target: [x86_64, i686, aarch64]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Build of plugin dll for ${{ matrix.build_target }}
      run: |
           rustup target add ${{ matrix.build_target }}-pc-windows-msvc
           cargo build --verbose --target ${{ matrix.build_target }}-pc-windows-msvc
           cargo build --release --target ${{ matrix.build_target }}-pc-windows-msvc

    - uses: olegtarasov/get-tag@v2.1.3
      id: tagName

    - name: zip artifacts for ${{ matrix.build_target }}
      run: 7z a rustnpp_${{ steps.tagName.outputs.tag }}_${{ matrix.build_target }}.zip .\target\${{ matrix.build_target }}-pc-windows-msvc\release\rustnpp.dll

    - name: Archive artifacts for ${{ matrix.build_target }}
      uses: actions/upload-artifact@v4
      with:
          name: rustnpp_${{ steps.tagName.outputs.tag }}_${{ matrix.build_target }}.zip
          path: rustnpp_${{ steps.tagName.outputs.tag }}_${{ matrix.build_target }}.zip

    - name: Create release on tagging
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
          files: rustnpp_${{ steps.tagName.outputs.tag }}_${{ matrix.build_target }}.zip

